### ISSUE TITLE
change the route name from namespace name to something static

### ISSUE THREAD

**Issue by alaypatel07** [konveyor/pvc-migrate#121]
The route name currently is the same as the name of the namespace.
we should probably change to a static name `rsync-stunnel` to avoid
running into dns issues. More info from in this slack [thread](https://coreos.slack.com/archives/CN1R97L4V/p1596633743474700)

**Comment by eriknelson** [comment]
Being very picky here, but what if that happens to already exist?

**Comment by alaypatel07** [comment]
@eriknelson I would say this is a good usecase for using `generatename: rsync-stunnel-`, my only reservation would be to check deletes work with generate name instead of regular name during cleanup. I know you are not a big fan of generateName, but makes sense here IMO

**Comment by eriknelson** [comment]
I'm not a fan of generate name when it's seeded from another k8s object name. I think this is exactly the scenario where it makes sense.

**Comment by alaypatel07** [comment]
generateName is not supported by k8s modules, the reason being, k8s module patches the resources by default when patching it requires name of the resource, since name of the resource is not yet determineable client-side, there is no way to use it currently. 

Hence thinking of generate a resource name like `pvc-migrate-<resource-kind>-<hash-namespace-10-chars>`, e.g `pvc-migrate-pod-1234567890`

**Comment by alaypatel07** [comment]
closing this via #124 and #122
