### ISSUE TITLE
Error on stunnel container due bad stunnel.conf

### ISSUE THREAD

**Issue by lcordero** [konveyor/pvc-migrate#131]
**Description:**
Double quotes on _[rsync]_ accept & connect ports, makes the container _ stunnel_ fail.

**Solution:**
Remove double quotes from here:
```
    [rsync]
    accept = "{{ stunnel_port }}"
    connect = "{{ rsyncd_port }}"
```

**Reference:** https://github.com/konveyor/pvc-migrate/blob/b7cb95edd6100e0883e41b5cf78ba92df315bd01/3_run_rsync/templates/stunnel.yml.j2#L19

**Comment by pranavgaikwad** [comment]
Caused due to https://github.com/konveyor/pvc-migrate/pull/126, related to #128 and #127
