### ISSUE TITLE
Add assertion for Kubeconfig

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/pvc-migrate#73]

**Comment by djwhatle** [comment]
Being solved in #74 , only stage 1 changes implemented for now, stage 2 and 3 to follow on Monday (or earlier if someone else wants to look into this).

**Comment by djwhatle** [comment]
- Add an assertion that user has correct active KUBECONFIG by reading the version endpoint (1: src, 2:dest, 3: dest)
- After assertion, copy KUBECONFIG to a safe location so that we are immune from KUBECONFIG changing underneath us during execution

**Comment by djwhatle** [comment]
Stage 2 and 3 changes still required.
