### ISSUE TITLE
Decouple ELB creation and running rsyncs, so we can quickly re-run rsyncs for flexibility of shorter outage windows.

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/pvc-migrate#89]
If ELBs remain a supported path, decouple their provisioning so that it's possible to have a scenario of:
1.  Create ELB ahead of time
2. Run a series of rsyncs for the namespace(s)
 a) Run 6 hours ahead of time to get bulk of data
 b) Run 2 hours ahead
 c) Run 30 mins ahead
 d) Take app down and have outage window
 e) Run rsync to pick up deltas
 f) Enable app to come back up

**Comment by pranavgaikwad** [comment]
Although #102 does not fix the mentioned issue of "decoupling" the phases, it addresses the reason why we want to de-couple in the first place. We no longer require ELB approach. For that reason, I am closing this issue.
