### ISSUE TITLE
Include a check for disk space before migrating

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/pvc-migrate#92]
Let's consider the current space being used by the source data and the amount of space available in destination.  
Sometimes the volume bound to a PVC is larger and the application may write past the PVC size.  Looking at PVC size only is not sufficient, we need to be aware of the PV size and the actual usage.

Issue shows up as:
> No space left on device (28)\nrsync error: error in file IO (code 11) at receiver.c(374) [receiver=3.1.3]

Notes from requestor:

>  ... thinking is if we can add an extra check when we generate the pvc-data.json file and identify if a PVC is full (or almost full - lets say >98% of capacity) to add extra 5Gbi to the PVC that we’ll create on the destination; and with it solve that issue.

**Comment by sseago** [comment]
One thing we haven't determined yet is when the volume size is larger than the PVC request, is this always reflected in the PV. In other words, if the volume is extended (potentially outside of OpenShift), will the PV size be updated too, or is it possible that even PV size isn't sufficient and we'll have to look at the filesystem itself? We should find an example of something like this from an in-use cluster. Lets look at PVC size, PV size, and mounted volume size and see if it's possible for mounted volume size to be greater than PV size.

**Comment by lcordero** [comment]
I think a possible solution could be do something like:
`$ oc -n <namespace> exec <pod> -- df -Ph /<pvc-name>`

From there extract the usage % of the pvc mounted on the pod; and with that, take the decision of increasing or not the value for the capacity on the pvc-data generation.

Here: https://github.com/konveyor/pvc-migrate/blob/master/1_pvc_data_gen/pvc_data_gen.py#L142

**Comment by sseago** [comment]
So in this case PV size won't help us -- it's actually the PVC. Using the filesystem size/utilization as @lcordero suggested will help, but even there, it may be hard for a 100% guarantee due to the fact that block sizes on src and target may be different.

**Comment by sseago** [comment]
Regarding the block size issue, it may be that to determine the appropriate target PVC size we need to connect to the src cluster node in stage 1 and look at filesystem size and percent usage, and then to handle the block size issue we could have a configurable parameter to specify "target percentage over source cluster usage". So if it was, say, 5% by default and the src PVC is 100GB, 99% full, this would result in a target cluster PVC of 104GB or so. As a configurable param, if we start seeing the "no space left on device" failures, we could bump it up to 10% for future runs.
